# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eleccion_profesor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_eleccion_profesor(object):
    def setupUi(self, eleccion_profesor):
        eleccion_profesor.setObjectName("eleccion_profesor")
        eleccion_profesor.resize(522, 352)
        eleccion_profesor.setFocusPolicy(QtCore.Qt.NoFocus)
        eleccion_profesor.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.elegirbtn = QtWidgets.QPushButton(eleccion_profesor)
        self.elegirbtn.setGeometry(QtCore.QRect(410, 310, 99, 27))
        self.elegirbtn.setObjectName("elegirbtn")
        self.disculpasLb = QtWidgets.QLabel(eleccion_profesor)
        self.disculpasLb.setGeometry(QtCore.QRect(20, 16, 391, 31))
        self.disculpasLb.setObjectName("disculpasLb")
        self.groupBox = QtWidgets.QGroupBox(eleccion_profesor)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 441, 251))
        self.groupBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 421, 220))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.celiaBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.celiaBtn.setObjectName("celiaBtn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.celiaBtn)
        self.martaBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.martaBtn.setObjectName("martaBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.martaBtn)
        self.nahuelBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.nahuelBtn.setObjectName("nahuelBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nahuelBtn)
        self.diegoVHBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.diegoVHBtn.setObjectName("diegoVHBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.diegoVHBtn)
        self.marcelosBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.marcelosBtn.setObjectName("marcelosBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.marcelosBtn)
        self.ricardoBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.ricardoBtn.setObjectName("ricardoBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ricardoBtn)
        self.samuelBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.samuelBtn.setObjectName("samuelBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.samuelBtn)
        self.pabloBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.pabloBtn.setObjectName("pabloBtn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pabloBtn)
        self.cristianBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.cristianBtn.setObjectName("cristianBtn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cristianBtn)
        self.brunoBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.brunoBtn.setObjectName("brunoBtn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.brunoBtn)
        self.valeriaBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.valeriaBtn.setObjectName("valeriaBtn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.valeriaBtn)
        self.diegoFBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.diegoFBtn.setObjectName("diegoFBtn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.diegoFBtn)
        self.gabrielBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.gabrielBtn.setObjectName("gabrielBtn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.gabrielBtn)
        self.marcelogBtn = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.marcelogBtn.setObjectName("marcelogBtn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.marcelogBtn)

        self.retranslateUi(eleccion_profesor)
        QtCore.QMetaObject.connectSlotsByName(eleccion_profesor)

    def retranslateUi(self, eleccion_profesor):
        _translate = QtCore.QCoreApplication.translate
        eleccion_profesor.setWindowTitle(_translate("eleccion_profesor", "Elegir Profesor"))
        self.elegirbtn.setText(_translate("eleccion_profesor", "Elegir"))
        self.disculpasLb.setText(_translate("eleccion_profesor", "<html><head/><body><p><span style=\" font-weight:600;\">¡Lo Sentimos! ¿En qué profesor estabas pensando?</span></p></body></html>"))
        self.groupBox.setTitle(_translate("eleccion_profesor", "Profesores"))
        self.celiaBtn.setText(_translate("eleccion_profesor", "Celia Cintas"))
        self.martaBtn.setText(_translate("eleccion_profesor", "Marta Saenz"))
        self.nahuelBtn.setText(_translate("eleccion_profesor", "Nahuel Defosse"))
        self.diegoVHBtn.setText(_translate("eleccion_profesor", "Diego Van Haaster"))
        self.marcelosBtn.setText(_translate("eleccion_profesor", "Marcelo Santander"))
        self.ricardoBtn.setText(_translate("eleccion_profesor", "Ricardo Lopez"))
        self.samuelBtn.setText(_translate("eleccion_profesor", "Samuel Almonacid"))
        self.pabloBtn.setText(_translate("eleccion_profesor", "Pablo Navarro"))
        self.cristianBtn.setText(_translate("eleccion_profesor", "Cristian Parise"))
        self.brunoBtn.setText(_translate("eleccion_profesor", "Bruno Zappellini"))
        self.valeriaBtn.setText(_translate("eleccion_profesor", "Valeria Entraigas"))
        self.diegoFBtn.setText(_translate("eleccion_profesor", "Diego Firmenich"))
        self.gabrielBtn.setText(_translate("eleccion_profesor", "Gabriel Ingravallo"))
        self.marcelogBtn.setText(_translate("eleccion_profesor", "Marcelo Gomez"))

